spring:
  application:
    name: HomeRun
  #profiles:
    #active: local
  flyway:
    enabled: false

app:
  version: "1.0.0"

notification:
  delivery:
    retry:
      exponential-base-delay: 10s
      max-backoff: 1m
      quota-fallback-delay: 1m
      jitter-ratio: 0.2
      max-concurrent-fcm: 4
      concurrency-retry-delay: 1s
